=== rj1004/HTML_CSS_JS_COLLAGE_LABS/Lab-7/schema1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="PlayerCollection">
	

			<xs:complexType>
				<xs:sequence>
					
						<xs:element name="Player" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="player-name" type="xs:string"/>
									<xs:element name="player-age" type="xs:integer"/>
									<xs:element name="betting-average" type="xs:integer"/>
									<xs:element name="highest-score" type="xs:integer"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					
			</xs:complexType>
	</xs:element>

</xs:schema>

=== rj1004/HTML_CSS_JS_COLLAGE_LABS/Lab-7/1.xml
<?xml version="1.0" encoding="UTF-8"?>



<PlayerCollection
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema1.xsd">

		
		<Player>

			<player-name>KL Rahul</player-name>
			<player-age>30</player-age>
			<betting-average>50</betting-average>
			<highest-score>200</highest-score>
		</Player>


		<Player>

			<player-name>KL Rahul</player-name>
			<player-age>30</player-age>
			<betting-average>50</betting-average>
			<highest-score>200</highest-score>
		</Player>

		<Player>

			<player-name>KL Rahul</player-name>
			<player-age>30</player-age>
			<betting-average>50</betting-average>
			<highest-score>200</highest-score>
		</Player>


		<Player>

			<player-name>KL Rahul</player-name>
			<player-age>30</player-age>
			<betting-average>50</betting-average>
			<highest-score>200</highest-score>
		</Player>
		
</PlayerCollection>
